### ISSUE TITLE
Confusion 

### ISSUE THREAD

**Issue by suv0dh** [strangerstudios/pmpro-network#11]
//set these values
define('PMPRO_NETWORK_MANAGE_SITES_SLUG', '/manage-sites/');    //change to relative path of your manage sites page if you are setting site credits > 1
$pmpro_network_non_site_levels = array(); // change to level id's that should not create a site: e.g. array('1','2','3')

I am confused with these statements.Please elaborate more about this.And is there page where the main site user can manage the membership with actions like suspense,deactivate ect ??

**Comment by strangerstudios** [comment]
We've since updated the pmpro-network add on to add a new setting on the Memberships -> Page Settings screen to set the manage sites page there. Similarly we've updated the plugin so you can set the number of "site credits" on the edit membership level page. You can set it to 0 for levels that shouldn't create sites. So you no longer need to add the code you shared.

The update with the site credits stuff is going out later today.
